/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.uniol.inf.is.odysseus.wrapper.actisense.SWIG;

public class ActisenseCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ActisenseCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ActisenseCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ActisenseJavaJNI.delete_ActisenseCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ActisenseJavaJNI.ActisenseCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ActisenseJavaJNI.ActisenseCallback_change_ownership(this, swigCPtr, true);
  }

  public void run(n2kMessage N2Kmsg) {
    if (getClass() == ActisenseCallback.class) ActisenseJavaJNI.ActisenseCallback_run(swigCPtr, this, n2kMessage.getCPtr(N2Kmsg), N2Kmsg); else ActisenseJavaJNI.ActisenseCallback_runSwigExplicitActisenseCallback(swigCPtr, this, n2kMessage.getCPtr(N2Kmsg), N2Kmsg);
  }

  public ActisenseCallback() {
    this(ActisenseJavaJNI.new_ActisenseCallback(), true);
    ActisenseJavaJNI.ActisenseCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
