/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.uniol.inf.is.odysseus.wrapper.actisense.SWIG;

public class ActisenseJavaJNI {
  public final static native long new_ActisenseWrapper(String jarg1, int jarg2) throws java.lang.RuntimeException;
  public final static native void delete_ActisenseWrapper(long jarg1);
  public final static native void ActisenseWrapper_start(long jarg1, ActisenseWrapper jarg1_);
  public final static native void ActisenseWrapper_stop(long jarg1, ActisenseWrapper jarg1_);
  public final static native void ActisenseWrapper_onMessage(long jarg1, ActisenseWrapper jarg1_, java.nio.ByteBuffer jarg2);
  public final static native void ActisenseWrapper_onMessageSwigExplicitActisenseWrapper(long jarg1, ActisenseWrapper jarg1_, java.nio.ByteBuffer jarg2);
  public final static native void ActisenseWrapper_director_connect(ActisenseWrapper obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ActisenseWrapper_change_ownership(ActisenseWrapper obj, long cptr, boolean take_or_release);

  public static void SwigDirector_ActisenseWrapper_onMessage(ActisenseWrapper self, java.nio.ByteBuffer buffer) {
    self.onMessage(buffer);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
