/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.uniol.inf.is.odysseus.wrapper.actisense.SWIG;

public class ActisenseWrapper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ActisenseWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ActisenseWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ActisenseJavaJNI.delete_ActisenseWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ActisenseWrapper(String comPort, int baudRate) throws java.lang.RuntimeException {
    this(ActisenseJavaJNI.new_ActisenseWrapper(comPort, baudRate), true);
  }

  public void start() {
    ActisenseJavaJNI.ActisenseWrapper_start(swigCPtr, this);
  }

  public void stop() {
    ActisenseJavaJNI.ActisenseWrapper_stop(swigCPtr, this);
  }

  public void delCallback() {
    ActisenseJavaJNI.ActisenseWrapper_delCallback(swigCPtr, this);
  }

  public void setCallback(ActisenseCallback cb) {
    ActisenseJavaJNI.ActisenseWrapper_setCallback(swigCPtr, this, ActisenseCallback.getCPtr(cb), cb);
  }

}
